### ISSUE TITLE
Stuck at ValueError when running "labgrid-client --help"

### ISSUE THREAD

**Issue by kahteik** [krevsbech/labgrid-docker-images#2]
After setting up the docker version of Labgrid client, I got the error below when I tried to run "labgrid-client --help".

```
root@866a8fc39706:/opt# labgrid-client --help
  Traceback (most recent call last):
    File "/opt/labgrid-venv/bin/labgrid-client", line 7, in <module>
      from labgrid.remote.client import main
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/__init__.py", line 1, in <module>
      from .target import Target
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/target.py", line 6, in <module>
      from .driver import Driver
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/driver/__init__.py", line 3, in <module>
      from .serialdriver import SerialDriver
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/driver/serialdriver.py", line 10, in <module>
      from ..resource import SerialPort, NetworkSerialPort
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/resource/__init__.py", line 7, in <module>
      from .udev import USBSerialPort
    File "/opt/labgrid-venv/lib/python3.5/site-packages/labgrid/resource/udev.py", line 148, in <module>
      class USBSerialPort(SerialPort, USBResource):
    File "/opt/labgrid-venv/lib/python3.5/site-packages/attr/_make.py", line 702, in attrs
      return wrap(maybe_cls)
    File "/opt/labgrid-venv/lib/python3.5/site-packages/attr/_make.py", line 671, in wrap
      builder = _ClassBuilder(cls, these, slots, frozen, auto_attribs)
    File "/opt/labgrid-venv/lib/python3.5/site-packages/attr/_make.py", line 371, in __init__
      attrs, super_attrs = _transform_attrs(cls, these, auto_attribs)
    File "/opt/labgrid-venv/lib/python3.5/site-packages/attr/_make.py", line 337, in _transform_attrs
      .format(a=a)
  ValueError: No mandatory attributes allowed after an attribute with a default value or factory.  Attribute in question: Attribute(name='match', default=NOTHING, validator=<instance_of validator for type <class 'dict'>>, repr=True, cmp=True, hash=False, init=True, metadata=mappingproxy({}), type=None, converter=None)
```

Tried to set up on Clear Linux and Fedora 25. Same error returned.

**Comment by krevsbech** [comment]
Just did a revised version where I am using the pinned versions  of dependencies from Labgrid master, see #3. 
Please try to test it in the staging environment provided now.
